<?php

declare(strict_types=1);

namespace Magento\SalesRule\Model;

class Coupon
{
    public const COUPON_TYPE_SPECIFIC_AUTOGENERATED = 1;

    public function getId() { return null; }
    public function setRuleId($ruleId) { return $this; }
    public function setCode($code) { return $this; }
    public function setUsageLimit($limit) { return $this; }
    public function setUsagePerCustomer($limit) { return $this; }
    public function setExpirationDate($date) { return $this; }
    public function setType($type) { return $this; }
    public function setIsPrimary($isPrimary) { return $this; }
    public function setDescription($description) { return $this; }
    public function getCode() { return null; }
    public function getExpirationDate() { return null; }
}
