<?php
declare(strict_types=1);

namespace ArtLounge\BentoEvents\Service;

use ArtLounge\BentoCore\Api\ConfigInterface;
use Magento\SalesRule\Api\RuleRepositoryInterface;
use Magento\SalesRule\Model\CouponFactory;
use Magento\SalesRule\Model\ResourceModel\Coupon as CouponResource;
use Magento\SalesRule\Model\ResourceModel\Coupon\CollectionFactory as CouponCollectionFactory;
use Magento\SalesRule\Model\Coupon;
use Psr\Log\LoggerInterface;

class CouponService
{
    private const CHARSET = 'ABCDEFGHJKLMNPQRSTUVWXYZ23456789';
    private const CODE_LENGTH = 6;
    private const MAX_COLLISION_RETRIES = 5;

    public function __construct(
        private readonly ConfigInterface $config,
        private readonly RuleRepositoryInterface $ruleRepository,
        private readonly CouponFactory $couponFactory,
        private readonly CouponResource $couponResource,
        private readonly CouponCollectionFactory $couponCollectionFactory,
        private readonly LoggerInterface $logger
    ) {
    }

    /**
     * Generate a unique coupon for an abandoned cart.
     *
     * @return array{code: string, expires_at: string}|null
     */
    public function generateForCart(int $quoteId, int $storeId): ?array
    {
        if (!$this->config->isCouponEnabled($storeId)) {
            return null;
        }

        $ruleId = $this->config->getCouponRuleId($storeId);
        if ($ruleId === null) {
            return null;
        }

        // Check for existing coupon for this quote (duplicate prevention)
        $existing = $this->findExistingCoupon($quoteId, $storeId);
        if ($existing !== null) {
            return $existing;
        }

        // Verify rule exists
        try {
            $this->ruleRepository->getById($ruleId);
        } catch (\Exception $e) {
            $this->logger->warning('Bento coupon: configured rule not found', [
                'rule_id' => $ruleId,
                'store_id' => $storeId,
                'error' => $e->getMessage()
            ]);
            return null;
        }

        $prefix = $this->config->getCouponPrefix($storeId);
        $lifetimeDays = $this->config->getCouponLifetimeDays($storeId);
        $expirationDate = (new \DateTime('+' . $lifetimeDays . ' days'))
            ->format('Y-m-d H:i:s');

        // Generate unique code with collision retry
        $code = null;
        for ($i = 0; $i < self::MAX_COLLISION_RETRIES; $i++) {
            $candidate = $prefix . '-' . $this->generateRandomSuffix();
            if (!$this->codeExists($candidate)) {
                $code = $candidate;
                break;
            }
        }

        if ($code === null) {
            $this->logger->warning('Bento coupon: failed to generate unique code after retries', [
                'quote_id' => $quoteId,
                'prefix' => $prefix
            ]);
            return null;
        }

        try {
            /** @var Coupon $coupon */
            $coupon = $this->couponFactory->create();
            $coupon->setRuleId($ruleId);
            $coupon->setCode($code);
            $coupon->setUsageLimit(1);
            $coupon->setUsagePerCustomer(1);
            $coupon->setExpirationDate($expirationDate);
            $coupon->setType(Coupon::COUPON_TYPE_SPECIFIC_AUTOGENERATED);
            $coupon->setIsPrimary(false);
            $coupon->setDescription('bento_quote_' . $quoteId);
            $this->couponResource->save($coupon);

            $this->logger->info('Bento coupon generated', [
                'code' => $code,
                'quote_id' => $quoteId,
                'rule_id' => $ruleId,
                'expires' => $expirationDate
            ]);

            return [
                'code' => $code,
                'expires_at' => (new \DateTime($expirationDate))->format('c')
            ];
        } catch (\Exception $e) {
            $this->logger->error('Bento coupon: failed to create coupon', [
                'quote_id' => $quoteId,
                'rule_id' => $ruleId,
                'error' => $e->getMessage()
            ]);
            return null;
        }
    }

    /**
     * Find an existing Bento coupon for a given quote (duplicate prevention).
     */
    private function findExistingCoupon(int $quoteId, int $storeId): ?array
    {
        $ruleId = $this->config->getCouponRuleId($storeId);
        if ($ruleId === null) {
            return null;
        }

        $collection = $this->couponCollectionFactory->create();
        $collection->addFieldToFilter('rule_id', $ruleId);
        $collection->addFieldToFilter('description', 'bento_quote_' . $quoteId);
        $collection->setPageSize(1);

        $coupon = $collection->getFirstItem();
        if ($coupon && $coupon->getId()) {
            return [
                'code' => $coupon->getCode(),
                'expires_at' => $coupon->getExpirationDate()
                    ? (new \DateTime($coupon->getExpirationDate()))->format('c')
                    : null
            ];
        }

        return null;
    }

    private function generateRandomSuffix(): string
    {
        $suffix = '';
        $max = strlen(self::CHARSET) - 1;
        for ($i = 0; $i < self::CODE_LENGTH; $i++) {
            $suffix .= self::CHARSET[random_int(0, $max)];
        }
        return $suffix;
    }

    private function codeExists(string $code): bool
    {
        $collection = $this->couponCollectionFactory->create();
        $collection->addFieldToFilter('code', $code);
        return $collection->getSize() > 0;
    }
}
