<?php
/**
 * Cart Recovery Controller
 *
 * Handles abandoned cart recovery links sent via Bento emails.
 * Validates the recovery token and restores the cart session.
 */

declare(strict_types=1);

namespace ArtLounge\BentoEvents\Controller\Cart;

use ArtLounge\BentoEvents\Model\RecoveryToken;
use Magento\Checkout\Model\Session as CheckoutSession;
use Magento\Customer\Model\Session as CustomerSession;
use Magento\Framework\App\Action\HttpGetActionInterface;
use Magento\Framework\App\RequestInterface;
use Magento\Framework\Controller\Result\RedirectFactory;
use Magento\Framework\Message\ManagerInterface as MessageManager;
use Magento\Framework\UrlInterface;
use Magento\Quote\Api\CartRepositoryInterface;
use Psr\Log\LoggerInterface;

class Recover implements HttpGetActionInterface
{
    public function __construct(
        private readonly RequestInterface $request,
        private readonly RedirectFactory $redirectFactory,
        private readonly CartRepositoryInterface $cartRepository,
        private readonly RecoveryToken $recoveryToken,
        private readonly CheckoutSession $checkoutSession,
        private readonly CustomerSession $customerSession,
        private readonly UrlInterface $urlBuilder,
        private readonly MessageManager $messageManager,
        private readonly LoggerInterface $logger
    ) {
    }

    /**
     * Execute cart recovery
     *
     * Token format: signed payload generated by RecoveryToken.
     */
    public function execute()
    {
        $redirect = $this->redirectFactory->create();
        $token = $this->request->getParam('recover');

        if (!$token) {
            return $redirect->setPath('checkout/cart');
        }

        $autoPayRequested = ((int)$this->request->getParam('autopay', 0)) === 1;
        $cartRedirectParams = $this->buildCartRedirectParams($autoPayRequested);

        try {
            $tokenData = $this->recoveryToken->parse($token);
            $quoteId = (int)$tokenData['quote_id'];
            $email = (string)$tokenData['email'];

            // Load the quote
            $quote = $this->cartRepository->get($quoteId);

            // Validate email matches
            if (strtolower($quote->getCustomerEmail()) !== strtolower($email)) {
                throw new \InvalidArgumentException('Token email mismatch');
            }

            // Check quote is still active
            if (!$quote->getIsActive()) {
                $this->messageManager->addNoticeMessage(
                    __('This cart has already been converted to an order or is no longer available.')
                );
                return $redirect->setPath('checkout/cart');
            }

            // Check quote has items
            if ($quote->getItemsCount() < 1) {
                $this->messageManager->addNoticeMessage(
                    __('This cart is empty.')
                );
                return $redirect->setPath('checkout/cart');
            }

            // Restore the cart to session
            // For guest carts, just set the quote in checkout session
            // For customer carts, the customer would need to log in first
            if ($quote->getCustomerId()) {
                // Customer cart - check if same customer is logged in
                $isSameCustomerLoggedIn = $this->customerSession->isLoggedIn()
                    && (int)$this->customerSession->getCustomerId() === (int)$quote->getCustomerId();

                if ($isSameCustomerLoggedIn) {
                    $this->checkoutSession->setQuoteId($quoteId);
                    $this->messageManager->addSuccessMessage(
                        __('Your cart has been restored.')
                    );
                } else {
                    // Different customer or not logged in
                    $couponParam = $this->request->getParam('coupon');
                    $recoveryUrl = $this->buildRecoveryUrl($token, $autoPayRequested, is_string($couponParam) ? $couponParam : null);
                    $this->setCustomerAuthRedirectUrls($recoveryUrl);

                    if ($this->customerSession->isLoggedIn()) {
                        $this->messageManager->addNoticeMessage(
                            __('You are signed in with a different account. Please sign in with the email used for this saved cart.')
                        );
                    } else {
                        $this->messageManager->addNoticeMessage(
                            __('Please log in to your account to access your saved cart.')
                        );
                    }

                    return $redirect->setPath('customer/account/login');
                }
            } else {
                // Guest cart - restore directly
                $this->checkoutSession->setQuoteId($quoteId);
                $this->messageManager->addSuccessMessage(
                    __('Your cart has been restored. Complete your purchase!')
                );
            }

            $this->logger->info('Cart recovered via Bento link', [
                'quote_id' => $quoteId,
                'email' => $email
            ]);

            // Auto-apply coupon if present in recovery URL
            $couponCode = $this->request->getParam('coupon');
            if ($couponCode && is_string($couponCode)) {
                try {
                    $quote->setCouponCode($couponCode);
                    $quote->collectTotals();
                    $this->cartRepository->save($quote);
                    $this->logger->info('Bento coupon auto-applied via recovery link', [
                        'quote_id' => $quoteId,
                        'coupon' => $couponCode
                    ]);
                } catch (\Exception $e) {
                    // Don't block cart recovery if coupon fails
                    $this->logger->warning('Bento coupon auto-apply failed', [
                        'quote_id' => $quoteId,
                        'coupon' => $couponCode,
                        'error' => $e->getMessage()
                    ]);
                }
            }

            return $redirect->setPath('checkout/cart', $cartRedirectParams);

        } catch (\InvalidArgumentException $e) {
            $this->logger->warning('Invalid cart recovery token', [
                'token' => $token,
                'error' => $e->getMessage()
            ]);
            $this->messageManager->addErrorMessage(
                __('The cart recovery link is invalid or has expired.')
            );
            return $redirect->setPath('checkout/cart');

        } catch (\Exception $e) {
            $this->logger->error('Cart recovery failed', [
                'token' => $token,
                'error' => $e->getMessage()
            ]);
            $this->messageManager->addErrorMessage(
                __('We could not restore your cart. Please try again or contact support.')
            );
            return $redirect->setPath('checkout/cart');
        }
    }

    /**
     * Build cart redirect params for a restored quote.
     */
    private function buildCartRedirectParams(bool $autoPayRequested): array
    {
        $query = [
            'bento_recovered' => 1
        ];

        if ($autoPayRequested) {
            $query['autopay'] = 1;
        }

        return [
            '_query' => $query
        ];
    }

    /**
     * Build a recovery URL for post-login continuation.
     */
    private function buildRecoveryUrl(string $token, bool $autoPayRequested, ?string $couponCode = null): string
    {
        $params = [
            'recover' => $token,
            '_nosid' => true
        ];

        if ($autoPayRequested) {
            $params['autopay'] = 1;
        }

        if ($couponCode !== null) {
            $params['coupon'] = $couponCode;
        }

        return $this->urlBuilder->getUrl('bento/cart/recover', $params);
    }

    /**
     * Set login return URLs on customer session with backward compatibility.
     */
    private function setCustomerAuthRedirectUrls(string $url): void
    {
        if (method_exists($this->customerSession, 'setBeforeAuthUrl')) {
            $this->customerSession->setBeforeAuthUrl($url);

            if (method_exists($this->customerSession, 'setAfterAuthUrl')) {
                $this->customerSession->setAfterAuthUrl($url);
            }

            return;
        }

        $this->customerSession->setData('before_auth_url', $url);
        $this->customerSession->setData('after_auth_url', $url);
    }
}
